---
title: "Section 6.1 Problems"
author: "Ryan Heslin"
date: "`r format(Sys.Date(), '%B %d, %Y')`"
output: 
  pdf_document:
    highlight: "kate"
    df_print: "kable"
---

\newcommand{\abcd}{\begin{bmatrix}a&b\\
c&d\end{bmatrix}}
\newcommand{\m}[1]{\begin{bmatrix}#1\end{bmatrix}}

\newcommand{\vect}[1]{\begin{pmatrix}#1\end{pmatrix}}

\newcommand{\meq}[1]{\begin{split}#1\end{split}}

\newcommand{\bym}[1]{#1\times{m}}

\newcommand{\nby}[1]{n\times{#1}}

\newcommand{\subsp}[2]{\Bigg\{\begin{bmatrix}#1\end{bmatrix}:#2\Bigg\}}

\newcommand{\proj}[2]{\text{proj}_#1(#2)}

\newcommand{\refl}[2]{\text{refl}_#1(#2)}

\newcommand{\sumn}{\sum_{i=1}^n}

 % 1: term 1 
 % 2: subscript 1 
 % 3: term 2 
 % 4: subscript 2 
 % 5. operation 
\newcommand{\dotsn}[5]{#1_{1}#3_{1}#5{#1}_{2}#3_{2}{#5}\dots{#5}#1_{#2}#3_{#4}}

\newcommand{\rot}[1]{
\begin{bmatrix}
\cos{(#1)} & -\sin{(#1)}\\

\sin{(#1)} & \cos{(#1)}\\
\end{bmatrix}
}
```{r setup, include=FALSE}

knitr::opts_chunk$set(
  echo = TRUE,
  comment = "",
  fig.pos = "",
  warning = FALSE,
  tidy = TRUE,
  fig.align = "center",
  highlight = TRUE
)

library(tidyverse)
library(rlang)
library(matador)
```

## 1.
\[x^2 + 4xy + 2y^2\]
This can be written $(x + 2y)^2 - 2y^2$

## 2.
a. Negative. $x^2 +6xy +5y^2$.

b. Semidefinite. $x^2 - 2xy + y^2$

c. PD. $2x^2 + 6xy + 5y^2$.

d. Not PD. $-x^2 +4xy - 8y^2$

For $b$, the valley runs along $x = y$.

## 3.

The equation is

\[(a - \lambda)(c - \lambda) = b^2\]
Both terms must ave the same sign. If $a > 0$ and
$ac > b^2$, then both $a$ and $c$ are positive.
Because $ac >b^2$ for this determinant equation to
be true both $a$ and $c$ must be reduced, so the
eigenvalues subtracted from them are positive.

## 4.
a. Maximum; all
four derivatives are increasing.
\[F = 1 + 4e^x-4x - 5x \sin y +6y^2\]

$$
  \begin{aligned}
    & F_{xx} = 4e^x\\
    & F_{YY} = 5x \sin y +12\\
    & F_{xy} = 5cosy\\
    & 4e^0 (5(0) \sin 0 +12) < 5 \cos 0\\
    & 0 < 5
  \end{aligned}
$$

b. Minimum
$$
\begin{aligned}
&F  = (x^2 - 2x) \cos y\\
&F_{xx}= 2 \cos y\\
& F_{yy} = x^2 \cos y - 2x \sin y\\
& F_{xy} = -2x \sin y + 2 \sin y\\
& (2 \cos \pi )(\cos \pi - 2 \sin \pi) > (-2 \sin \pi + 2 \sin \pi)^2\\
& (-2)(-1) > 0\\
& 2 > 0
\end{aligned}
$$


a. $|b| < 9$.

b. The $LDL^T$ is:

$$
\begin{aligned}
\begin{bmatrix}
  1 & 0\\
  b & 1
\end{bmatrix}
\begin{bmatrix}
  1 & 0\\
  0 & 9-b^2
\end{bmatrix}
\begin{bmatrix}
  1 & b\\
  0 & 1
\end{bmatrix}
\end{aligned}
$$

d. Some googling tells me the minimizing solution is
given by the eigenvector of the minimum eigenvalue.
If $b=3 \implies \lambda_{min} = 0$, that's a unit
vector of the kernel basis $\m{1\\-1/3}$

## 6.

\[
A = \begin{bmatrix}
  2 & 2\\
  2 & 1
\end{bmatrix}
\]

## 7.

$$
A_1 = \begin{bmatrix}
  1 & -1 & -1\\
  -1 & 1 & 1\\
  -1 & 1 & 1
\end{bmatrix}
$$

The function of this matrix is 0 where $x_1=1$
and $x_2 = 1$ and $x_3 =0$ or vice versa, from its
kernel.
$$
  \begin{aligned}
    & A_2 = LL^T\\
    & L =\begin{bmatrix}
      1 & 0 & 0\\
      -1 & 1 & 0\\
      -1 & -3 & 1
    \end{bmatrix}
  \end{aligned}
$$

## 8.

from the inverse formula, the quadratic form
of the inverse is
\[ \frac{cx^2 -2bxy +a^2}{ac-b^2}\]
In terms
of the usual rules, this means
The test is \[ \frac{c}{ac  ^x} >  \frac{b^2}{a^2c^2 - 2b^2ac + b^4}\]

## 9.

The factorization for $3(x_1 + 2x_2)^2 + 4x_2^2$ is:

 $$ 
   \begin{aligned} 
     & L = \begin{bmatrix} 
       1 & 0 & 0\\ 
       2 & 1 & 0\\ 
       0 & 0 & 1 
     \end{bmatrix}\\ 
     & D = \begin{bmatrix} 
       3 & 0 & 0\\ 
       0 & 4 & 0\\ 
       0 & 0 & 0 
     \end{bmatrix} 
   \end{aligned} 
 $$ 

The elements of $d$ are the coefficients of the
diagonal terms, and the off-diagonals of $l$ are
the interaction coefficients

## 10.

 $$ 
   \begin{aligned} 
     & a = \begin{bmatrix} 
       p & q\\ 
       q & r 
     \end{bmatrix} 
   & a^2 = 
 \begin{bmatrix} 
   p^2 +q^2 & pq + qr\\ 
   pq + qr & q^2 + r^2 
 \end{bmatrix} 
 \end{aligned} 
 $$ 

If the matrix is singular, than for $a^2$ $b^2 = p^2q^2 + 2q^4 + 2q^2r^2$, always positive and potentially equal to $p^2 + q^2$.

## 11.
a. $\det a = ac - |b|^2$, with pivots $a$ and $c - \frac{|b|}{a}$
b. $a|x_1|^2 + 2 Re b |x_1|x_2 + c|x_2| = a|x + \frac{bx_2}{a}|^2 + |c - \frac{|b|}{a}||x_2|$

c. Given this, the second pivot must be positive,e ensuring
the matrix is positive semi-definite.
d. The first is not, since $2 > = 1^2 + 1^2$, but the second its, since $18 > 4^2 + 1^2$

## 12.

$$
  \begin{aligned}
    & f = x^2y^2 - 2x - 2y\\
    & f_{xx} = 2y^2\\
    & f_{yy} = 2x^2\\
    & f_{xy} = 4xy
  \end{aligned}
$$

at $(1,1)$:

$$
  \begin{aligned}
    & 2(1^2)2(1^2) > 4(1)(1)\\
    & 4 = 4
  \end{aligned}
$$

Not quite a minimum
or maximum.

## 13.

$$
  \begin{aligned}
    & f_{x} = 2ax + 2by\\
    &f_{xx} = 2a\\
    & f_y = 2(bx + cy)\\
    & f_{yy} = 2c
  \end{aligned}
$$
Since the original function's partial derivatives are $2x$ and $2y$ and $2$, $a$, $b$, and $c$ must be greater than 1.

## 14.
Do they have two positive eigenvalues
a. No. $x = \m{1/4 \\ -1/4}$

b. No. $x = \m{1 \\ 1}$

c. No. No $x$ exists because it's positive
semidefinite.

d. Yes.
None exists; it's pd.

## 15.

a. $f = a^2 + 4xy + 9^2$ and $ f = (x +2y)^2 + (9-4)y^2$

b. $f = x^2 + 6xy + 9y^2 $ and $f = (x +3y)^2$.

## 16.

This is not a minimum:
$$
  \begin{aligned}
    & f_{xx} = 2\\
    & f_{yy} = 6\\
    & f_{xy} = 4\\
    & 2(6) < 4^2
  \end{aligned}
$$

As a difference of squares, $f = x^2 + 4xy + 3y^2 = (x + 2y)^2 - y^2$. so $\m{-2\\1}$, for example, gives $z = -1$.

## 17.
$$
  \begin{aligned}
    & x^Ta^Tax\\
    & = (ax)^T(ax)\\
  \end{aligned}
$$

Clearly this is always positive for
nonzero $x$.

## 18.

All are clearly PD.

 $$ 
   \begin{aligned} 
     & a^ta = \begin{bmatrix} 
       1 & 2\\ 
       2 & 13 
     \end{bmatrix}\\ & a^ta =\begin{bmatrix} 
       5 & 4\\ 
       4 & 5 
     \end{bmatrix}\\ 
     & a^ta  = \begin{bmatrix} 
       2 & 3 & 3\\ 
       3 & 5 & 4\\ 
       3 & 4 & 5 
     \end{bmatrix} 
   \end{aligned} 
 $$ 

## 19.
$4(x_1 - x_2 + 2x_3)^2$ expands to

\[4x_1^2 - 4x_1x_2 + 8 x_1x_3  - 4x_1 x_2 + 4 x_2 ^2 + 8x_2 x_3 + 8 x_1 x_3 - 8 x_2 x_3 + 32 x_3 ^2\]
implying a matrix of

\[
\begin{bmatrix}
  4 & -4 & 8\\
  -4 & 4 & -8\\
  8 & -8 & 32
\end{bmatrix}
\]

determinant is 0, rank is 2, not bothering with the eigenvalues.

## 20.

 $$ 
   \begin{aligned} 
     & a_1 = \begin{bmatrix} 
       9/4x^2 + 2y    & 2x\\ 
       2x & 2 
     \end{bmatrix}\\ 
     & a_2 = \begin{bmatrix} 
       6x & 1\\ 
       1 & 0 
     \end{bmatrix} 
   \end{aligned} 
 $$ 
 
## 21.

The first derivatives have opposite signs: one function is increasing,
the other decreasing.

## 22.

For $f(x) = 4x^2 + 12xy + cy^2$ the derivatives matrix is

\[
 \begin{bmatrix}
  8 & 12\\
  12 & 2c
\end{bmatrix}
\]

which is positive definite where

$$
  \begin{aligned}
    & 16c > 144\\
    & c > 9
  \end{aligned}
$$