---
title: "Section 7.6 Problems"
author: "Ryan Heslin"
date: "`r format(Sys.Date(), '%B %d, %Y')`"
output: 
  pdf_document:
    highlight: "kate"
    df_print: "kable"
---

 <!-- Standard custom LaTeX commands -->
\newcommand{\abcd}{\begin{bmatrix}a&b\\
c&d\end{bmatrix}}
\newcommand{\m}[1]{\begin{bmatrix}#1\end{bmatrix}}

\newcommand{\vect}[1]{\begin{pmatrix}#1\end{pmatrix}}

\newcommand{\meq}[1]{\begin{split}#1\end{split}}

\newcommand{\bym}[1]{#1\times{m}}

\newcommand{\nby}[1]{n\times{#1}}

\newcommand{\subsp}[2]{\Bigg\{\begin{bmatrix}#1\end{bmatrix}:#2\Bigg\}}

\newcommand{\proj}[2]{\text{proj}_#1(#2)}

\newcommand{\refl}[2]{\text{refl}_#1(#2)}

\newcommand{\sumn}{\sum_{i=1}^n}

<!-- % 1: term 1 -->
<!-- % 2: subscript 1 -->
<!-- % 3: term 2 -->
<!-- % 4: subscript 2 -->
<!-- % 5. operation -->
\newcommand{\dotsn}[5]{#1_{1}#3_{1}#5{#1}_{2}#3_{2}{#5}\dots{#5}#1_{#2}#3_{#4}}

```{r setup, include=FALSE}

knitr::opts_chunk$set(
  echo = TRUE,
  comment = "",
  fig.pos = "",
  warning = FALSE,
  tidy = TRUE,
  fig.align = "center",
  highlight = TRUE
)

library(tidyverse)
library(rlang)
```

Is the zero state a stable equilibrium?

##1.

Stable, since the diagonal eigenvalues are less than 0.

##2.

Not stable.

## 3.

\[
  \begin{aligned}
    & \lambda^2 - 1.6 \lambda + 1.13 \\
    & \lambda = .8 \pm .98i
  \end{aligned}
\]

Since `r paste0("$1.6^2 + .98^2 = ", .8^2 + .98^2, "$ ")`, not stable.

# 11.

$-1.1 \leq k \leq .1$.

## 12.

$|k| \leq .8$

## 13.

All possible values.

## 14.

$|k| < 1/2$

## 15.

No possible values, since $\lambda_1 + \lambda_2 = 2$ means one or both has absolute value greater than 1.

## 16.

## 17.

$\lambda = .6 \pm .8i$

I pick $.6 + .8i$.

$$
\begin{aligned}
& S = \begin{bmatrix}
  1 & 1\\
  -i & i
\end{bmatrix}\\
& v = \begin{bmatrix}
  1\\
  0
\end{bmatrix} +
i \begin{bmatrix}
  0\\
  -1
\end{bmatrix}\\
& S = \begin{bmatrix}
  0 & 1\\
  -1 & 0
\end{bmatrix}
\end{aligned}
$$

\[c= S^{-1} \begin{bmatrix}
  0\\
  1
\end{bmatrix}=  \begin{bmatrix}
  -1\\
  0
\end{bmatrix}\]

The big dumb formula, with $\theta = \arctan .8/.6 \approx .92$:

\[
  \begin{aligned}
    & u_{k+1} = (1^k) \begin{bmatrix}
      0 & 1\\
      -1 & 0
    \end{bmatrix} \begin{bmatrix}
      \cos 1^k \theta  & -\sin 1^k \theta\\
      \sin 1^k \theta &  \cos 1^k \theta
    \end{bmatrix}
    \begin{bmatrix}
      -1\\
      0
    \end{bmatrix}\\
    & = \begin{bmatrix}
      \sin \theta & \cos \theta\\
      - \cos \theta & \sin \theta
    \end{bmatrix}
    \begin{bmatrix}
      -1\\
      0
    \end{bmatrix}\\
    & = \begin{bmatrix}
     - \sin \theta\\
       \cos \theta
    \end{bmatrix}
  \end{aligned}
\]

Interesting  - is $r$ always the square root of the determinant for skew-symmetric?

## 19.

\[ A =  \begin{bmatrix}
  2 & -3\\
  3 & 2
\end{bmatrix}\]

$\lambda = 2 \pm 3i$

\[
  \begin{aligned}
    & S_1 = \begin{bmatrix}
      1\\
      -i
    \end{bmatrix}\\
  &s = \begin{bmatrix}
    0 & 1\\
    -1 & 0
  \end{bmatrix} \\
  & c = S^{-1}x_0 = \begin{bmatrix}
    -1\\
    0
  \end{bmatrix}\\
  & \theta = \arctan \frac{3}{2} = `r atan(3/2)`\\
  & r = \sqrt {13}
    \end{aligned}
  \]

\[
  \begin{aligned}
    & u_{k+1} = \sqrt {13}^k \begin{bmatrix}
      0 & 1\\
      -1 & 0
    \end{bmatrix}
    \begin{bmatrix}
      \cos \theta k & -\sin \theta k\\
      \sin \theta k & \cos \theta k
    \end{bmatrix}
    \begin{bmatrix}
      -1\\
      0
    \end{bmatrix}\\
    & =\sqrt{13}^k \begin{bmatrix}
      - \cos \theta k\\
      \sin \theta k
    \end{bmatrix}
  \end{aligned}
\]

## 21.


\[A = \begin{bmatrix}
  1 & 5\\
  -2 & 7
\end{bmatrix}\]

$$
  \begin{aligned}
    & S_1 = \begin{bmatrix}
      1\\
      3/5 + 5/i
    \end{bmatrix}\\
    & S = \begin{bmatrix}
      0 & 1\\
      1/5 & 3/5
    \end{bmatrix}\\
    & r = \sqrt {17} \\
    & \theta = \arctan \frac{1}{4}\\
    & c = -5\begin{bmatrix}
      -1\\
      0
    \end{bmatrix} = \begin{bmatrix}
      5\\
      0
    \end{bmatrix}
  \end{aligned}
$$

\[
  \begin{aligned}
    & u_{k+1} = \sqrt {17} \begin{bmatrix}
      0 & 1\\
      1/5 & 3/5
    \end{bmatrix}
    \begin{bmatrix}
      \cos \theta k & -\sin \theta k\\
      \sin \theta k & \cos \theta k
    \end{bmatrix}
    \begin{bmatrix}
      5\\
      0
    \end{bmatrix}\\
    & = \sqrt{17} \begin{bmatrix}
      0 & 1\\
      1/5 & 3/5
    \end{bmatrix} 
    \begin{bmatrix}
      5 \cos \theta k  \\
      5 \sin \theta
    \end{bmatrix}\\
    & = \sqrt{17} 
    \begin{bmatrix}
      5 \sin  \theta k\\
      \cos \theta k + 3 \sin \theta k
    \end{bmatrix}
  \end{aligned}
\]

## 25.

Unstable. If $A$ is stable,e ach $\lambda$ must be less than 1 in absolute value, so $1 / \lambda$ of the inverse must be greater.

## 26.

Stable, since $A^T$ has the same eigenvalues as $A$.

## 27.

Stable, since the eigenvalues just have to be less than 1 in absolute value.

## 28.

Unstable. \[
  \begin{aligned}
    & |\lambda| < 1\\
    & |\lambda -2| < -1 
  \end{aligned}
\]

## 29.

Stable if  $\lambda < 0$, the square is smaller.

## 30.

## 31.

By the rule that $|\lambda| < 1$ for stability:

\[
  \begin{aligned}
    & |tr A| -1 < \det A <1 \\
    & |\lambda_1 + \lambda_2| -1 < \lambda_1 \lambda_2 < 1\\
    & 1 < 1 <1
  \end{aligned}
\]

This holds only if both have absolute value less than 1.

## 33.

If $x_0$ is real, then $ c_1iw = -c_2iw$ - the complex components cancel. Since $\bar c_1 iw = -c_1 iw$, that means $c_1 = \bar c_2$.

## 34.

a. It cannot be stable, because at least one iegenvalue is too large. 

b. If $| \det A | < 1$, it may be stable. Otherwise, at least one eigenvalue is too large.

## 35.

a. $u_{k+1} = Au_k$ may be rewritten $A^k u_0$. Since all eigenvalues are less than 1 in absolute value, $A$ is stable at zero, so $A^k$ approaches 0 as $k$ increases. Thus the length of the vector dieminishes with each iteration

b. No. All eigenvalues are 1, so the matrix is unstable and approaches no limit.

## 38.

a.
\[
  \begin{aligned}
    & x = Ax +b\\
    & Ax = x -b\\
    & x = A^{-1}(x -b)\\
    & x = \frac{1}{\lambda}(x -b)
  \end{aligned}
\]

b. If $x$ is an eigenvector with a nonzero eigenvalue.

## 39.

The eigenvector with highest $\lambda$ is $/m{1\\2}$, so
\[ \begin{bmatrix}
  1\\
  2
\end{bmatrix} +
\begin{bmatrix}
  1\\
  2
\end{bmatrix} = \begin{bmatrix}
  2\\
  4
\end{bmatrix}\]
because $\m{1\\2}$ gets added after _each iteration_.